LABEL_TO_IDX = {
    "AHU": 0,
    "AV recorder": 1,
    "CD player": 2,
    "CE appliance": 3,
    "CRT screen": 4,
    "Commercial appliance": 5,
    "DAC": 6,
    "DVD player": 7,
    "HTPC": 8,
    "ICT appliance": 9,
    "LED lamp": 10,
    "RF booster": 11,
    "UPS": 12,
    "USB hub": 13,
    "acquarium pump": 14,
    "active speaker": 15,
    "active subwoofer": 16,
    "air conditioner": 17,
    "air handling unit": 18,
    "appliance": 19,
    "arc lamp": 20,
    "audio amplifier": 21,
    "audio system": 22,
    "baby monitor": 23,
    "blu-ray player": 24,
    "boiler": 25,
    "bottle warmer": 26,
    "bouncy castle pump": 27,
    "breadmaker": 28,
    "broadband router": 29,
    "cassette deck": 30,
    "charger": 31,
    "clothes iron": 32,
    "coffee maker": 33,
    "cold appliance": 34,
    "compact fluorescent lamp": 35,
    "component": 36,
    "compressor": 37,
    "computer": 38,
    "computer monitor": 39,
    "cooker": 40,
    "dehumidifier": 41,
    "desktop computer": 42,
    "digital picture frame": 43,
    "dimmer": 44,
    "dish washer": 45,
    "dishwasher": 46,
    "door bell": 47,
    "drill": 48,
    "electric air heater": 49,
    "electric blanket": 50,
    "electric furnace": 51,
    "electric grill": 52,
    "electric heating element": 53,
    "electric hot tub heater": 54,
    "electric oven": 55,
    "electric shower heater": 56,
    "electric space heater": 57,
    "electric stove": 58,
    "electric swimming pool heater": 59,
    "electric vehicle": 60,
    "electric water heater": 61,
    "electric water heating appliance": 62,
    "elevator": 63,
    "ethernet hub": 64,
    "ethernet switch": 65,
    "external hard disk": 66,
    "fan": 67,
    "fax": 68,
    "flat screen": 69,
    "fluorescent lamp": 70,
    "food processor": 71,
    "food steamer": 72,
    "freezer": 73,
    "fridge": 74,
    "fridge freezer": 75,
    "fryer": 76,
    "games console": 77,
    "garden sprinkler": 78,
    "gas discharge lamp": 79,
    "grill": 80,
    "hair dryer": 81,
    "hair straighteners": 82,
    "heat pump": 83,
    "heating appliance": 84,
    "hot tub pump": 85,
    "immersion heater": 86,
    "incandescent lamp": 87,
    "jacuzzi pump": 88,
    "kettle": 89,
    "kitchen aid": 90,
    "lamp": 91,
    "laptop computer": 92,
    "large printer": 93,
    "light": 94,
    "lighting component": 95,
    "linear fluorescent lamp": 96,
    "manual misc appliance": 97,
    "massage bed": 98,
    "microwave": 99,
    "mobile phone charger": 100,
    "modem": 101,
    "motor": 102,
    "motorised chair": 103,
    "multi-function device": 104,
    "musical instrument": 105,
    "network attached storage": 106,
    "oven": 107,
    "paper shredder": 108,
    "photocopier": 109,
    "plate warmer": 110,
    "pond pump": 111,
    "printer": 112,
    "projector": 113,
    "radio": 114,
    "record deck": 115,
    "rice cooker": 116,
    "running machine": 117,
    "saw": 118,
    "scanner": 119,
    "screen": 120,
    "security alarm": 121,
    "server computer": 122,
    "set top box": 123,
    "sewing machine": 124,
    "shower pump": 125,
    "slow cooker": 126,
    "small cooking appliance": 127,
    "small printer": 128,
    "small resistive cooking appliance": 129,
    "smoke alarm": 130,
    "sockets": 131,
    "solar thermal pumping station": 132,
    "soldering iron": 133,
    "spin dryer": 134,
    "steriliser": 135,
    "stove": 136,
    "subpanel": 137,
    "sun bed": 138,
    "swimming pool pump": 139,
    "tablet computer charger": 140,
    "television": 141,
    "toasted sandwich maker": 142,
    "toaster": 143,
    "trouser press": 144,
    "tumble dryer": 145,
    "unknown": 146,
    "vacuum cleaner": 147,
    "video sender": 148,
    "washer dryer": 149,
    "washing machine": 150,
    "waste disposal unit": 151,
    "water filter": 152,
    "water pump": 153,
    "wet appliance": 154,
    "wireless phone charger": 155,
    "yoghurt maker": 156,
}

IDX_TO_LABEL = {v: k for (k, v) in LABEL_TO_IDX.items()}

NUM_CLASSES = len(LABEL_TO_IDX)
